env:
  shared-node-browser: true
extends:
  - "eslint:recommended"
  - "plugin:@docusaurus/recommended"
overrides:
  - files:
      - "*.md"
      - "*.mdx"
    extends:
      - "plugin:mdx/recommended"
      - "plugin:react/recommended"
    parser: "eslint-mdx"
    rules:
      no-undef: "off"
      no-unused-expressions: "off"
  - files:
      - "*.ts"
      - "*.tsx"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:react/recommended"
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaFeatures:
        jsx: true
      ecmaVersion: "latest"
      project: "tsconfig.json"
      sourceType: "module"
    plugins:
      - "@typescript-eslint"
    rules:
      "@typescript-eslint/no-floating-promises":
        - error
        - ignoreIIFE: true
          ignoreVoid: true
      "@typescript-eslint/no-unused-vars":
        - error
        - argsIgnorePattern: ^_
          varsIgnorePattern: ^_
      "react/react-in-jsx-scope": "off"
root: true
settings:
  react:
    version: "detect"
