env:
  shared-node-browser: true
extends:
  - "eslint:recommended"
  - "plugin:@docusaurus/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:mdx/recommended"
  - "plugin:react/recommended"
overrides:
  - files:
      - "*.md"
      - "*.mdx"
    parser: "eslint-mdx"
    rules:
      no-unused-expressions: "off"
  - files:
      - "*.ts"
      - "*.tsx"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "tsconfig.json"
    plugins:
      - "@typescript-eslint"
    rules:
      "@typescript-eslint/no-floating-promises":
        - error
        - ignoreIIFE: true
          ignoreVoid: true
      "@typescript-eslint/no-unused-vars":
        - error
        - argsIgnorePattern: ^_
          varsIgnorePattern: ^_
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: "latest"
root: true
rules:
  "react/react-in-jsx-scope": "off"
settings:
  react:
    version: "detect"
