env:
  shared-node-browser: true
extends:
  - "eslint:recommended"
  - "plugin:@docusaurus/recommended"
overrides:
  - files:
      - "*.md"
      - "*.mdx"
    extends:
      - "plugin:mdx/recommended"
      - "plugin:react/recommended"
    parser: "eslint-mdx"
    rules:
      no-undef: "off"
      no-unused-expressions: "off"
      react/jsx-no-undef: "off"
root: true
settings:
  react:
    version: "detect"
