printWidth: 120
plugins: ["@trivago/prettier-plugin-sort-imports"]
trailingComma: "all"

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: ["*.ts", "*.tsx"]
    options:
      # https://github.com/trivago/prettier-plugin-sort-imports#importorder
      importOrder:
        - "^react"
        - "^@emotion"
        - "<THIRD_PARTY_MODULES>"
        - "<THIRD_PARTY_TS_TYPES>"
        - "<TS_TYPES>"
        - "^[./]"
      importOrderSeparation: false
      importOrderSortSpecifiers: true
      parser: "typescript"
