/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  conceptsSidebar: [{ type: "autogenerated", dirName: "concepts" }],
  contractsSidebar: [{ type: "autogenerated", dirName: "contracts" }],
  faqSidebar: [{ type: "autogenerated", dirName: "faq" }],
};

module.exports = sidebars;
