import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * By default, Docusaurus generates a sidebar from the docs folder structure, but we can
 * customize it to include only the desired sections.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [{ dirName: "api", type: "autogenerated" }],
  appSidebar: [{ dirName: "apps", type: "autogenerated" }],
  conceptsSidebar: [{ dirName: "concepts", type: "autogenerated" }],
  guidesSidebar: [{ dirName: "guides", type: "autogenerated" }],
  referencesSidebar: [{ dirName: "reference", type: "autogenerated" }],
  supportSidebar: [{ dirName: "support", type: "autogenerated" }],
};

export default sidebars;
